#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abituriyent.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Universitet")]
	public partial class CedvellerDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTehsilFormasi(TehsilFormasi instance);
    partial void UpdateTehsilFormasi(TehsilFormasi instance);
    partial void DeleteTehsilFormasi(TehsilFormasi instance);
    partial void InsertFakulte(Fakulte instance);
    partial void UpdateFakulte(Fakulte instance);
    partial void DeleteFakulte(Fakulte instance);
    partial void InsertIxtisa(Ixtisa instance);
    partial void UpdateIxtisa(Ixtisa instance);
    partial void DeleteIxtisa(Ixtisa instance);
    partial void InsertQrup(Qrup instance);
    partial void UpdateQrup(Qrup instance);
    partial void DeleteQrup(Qrup instance);
    partial void InsertUniversitet(Universitet instance);
    partial void UpdateUniversitet(Universitet instance);
    partial void DeleteUniversitet(Universitet instance);
    #endregion
		
		public CedvellerDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["UniversitetConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CedvellerDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CedvellerDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CedvellerDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CedvellerDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TehsilFormasi> TehsilFormasis
		{
			get
			{
				return this.GetTable<TehsilFormasi>();
			}
		}
		
		public System.Data.Linq.Table<Fakulte> Fakultes
		{
			get
			{
				return this.GetTable<Fakulte>();
			}
		}
		
		public System.Data.Linq.Table<Ixtisa> Ixtisas
		{
			get
			{
				return this.GetTable<Ixtisa>();
			}
		}
		
		public System.Data.Linq.Table<Qrup> Qrups
		{
			get
			{
				return this.GetTable<Qrup>();
			}
		}
		
		public System.Data.Linq.Table<Universitet> Universitets
		{
			get
			{
				return this.GetTable<Universitet>();
			}
		}
		
		public System.Data.Linq.Table<Umumi> Umumis
		{
			get
			{
				return this.GetTable<Umumi>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TehsilFormasi")]
	public partial class TehsilFormasi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TehsilFormasiId;
		
		private string _TAd;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTehsilFormasiIdChanging(int value);
    partial void OnTehsilFormasiIdChanged();
    partial void OnTAdChanging(string value);
    partial void OnTAdChanged();
    #endregion
		
		public TehsilFormasi()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TehsilFormasiId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TehsilFormasiId
		{
			get
			{
				return this._TehsilFormasiId;
			}
			set
			{
				if ((this._TehsilFormasiId != value))
				{
					this.OnTehsilFormasiIdChanging(value);
					this.SendPropertyChanging();
					this._TehsilFormasiId = value;
					this.SendPropertyChanged("TehsilFormasiId");
					this.OnTehsilFormasiIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAd", DbType="NVarChar(10)")]
		public string TAd
		{
			get
			{
				return this._TAd;
			}
			set
			{
				if ((this._TAd != value))
				{
					this.OnTAdChanging(value);
					this.SendPropertyChanging();
					this._TAd = value;
					this.SendPropertyChanged("TAd");
					this.OnTAdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Fakulte")]
	public partial class Fakulte : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _FakulteId;
		
		private string _FAd;
		
		private System.Nullable<int> _FTehsilFormasiId;
		
		private System.Nullable<int> _FUniversitetId;
		
		private System.Nullable<int> _FIxtisasId;
		
		private string _GirisBali;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFakulteIdChanging(int value);
    partial void OnFakulteIdChanged();
    partial void OnFAdChanging(string value);
    partial void OnFAdChanged();
    partial void OnFTehsilFormasiIdChanging(System.Nullable<int> value);
    partial void OnFTehsilFormasiIdChanged();
    partial void OnFUniversitetIdChanging(System.Nullable<int> value);
    partial void OnFUniversitetIdChanged();
    partial void OnFIxtisasIdChanging(System.Nullable<int> value);
    partial void OnFIxtisasIdChanged();
    partial void OnGirisBaliChanging(string value);
    partial void OnGirisBaliChanged();
    #endregion
		
		public Fakulte()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FakulteId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int FakulteId
		{
			get
			{
				return this._FakulteId;
			}
			set
			{
				if ((this._FakulteId != value))
				{
					this.OnFakulteIdChanging(value);
					this.SendPropertyChanging();
					this._FakulteId = value;
					this.SendPropertyChanged("FakulteId");
					this.OnFakulteIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAd", DbType="NVarChar(100)")]
		public string FAd
		{
			get
			{
				return this._FAd;
			}
			set
			{
				if ((this._FAd != value))
				{
					this.OnFAdChanging(value);
					this.SendPropertyChanging();
					this._FAd = value;
					this.SendPropertyChanged("FAd");
					this.OnFAdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FTehsilFormasiId", DbType="Int")]
		public System.Nullable<int> FTehsilFormasiId
		{
			get
			{
				return this._FTehsilFormasiId;
			}
			set
			{
				if ((this._FTehsilFormasiId != value))
				{
					this.OnFTehsilFormasiIdChanging(value);
					this.SendPropertyChanging();
					this._FTehsilFormasiId = value;
					this.SendPropertyChanged("FTehsilFormasiId");
					this.OnFTehsilFormasiIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FUniversitetId", DbType="Int")]
		public System.Nullable<int> FUniversitetId
		{
			get
			{
				return this._FUniversitetId;
			}
			set
			{
				if ((this._FUniversitetId != value))
				{
					this.OnFUniversitetIdChanging(value);
					this.SendPropertyChanging();
					this._FUniversitetId = value;
					this.SendPropertyChanged("FUniversitetId");
					this.OnFUniversitetIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIxtisasId", DbType="Int")]
		public System.Nullable<int> FIxtisasId
		{
			get
			{
				return this._FIxtisasId;
			}
			set
			{
				if ((this._FIxtisasId != value))
				{
					this.OnFIxtisasIdChanging(value);
					this.SendPropertyChanging();
					this._FIxtisasId = value;
					this.SendPropertyChanged("FIxtisasId");
					this.OnFIxtisasIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GirisBali", DbType="NVarChar(15)")]
		public string GirisBali
		{
			get
			{
				return this._GirisBali;
			}
			set
			{
				if ((this._GirisBali != value))
				{
					this.OnGirisBaliChanging(value);
					this.SendPropertyChanging();
					this._GirisBali = value;
					this.SendPropertyChanged("GirisBali");
					this.OnGirisBaliChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ixtisas")]
	public partial class Ixtisa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IxtisasId;
		
		private System.Nullable<int> _IQrupId;
		
		private string _IAd;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIxtisasIdChanging(int value);
    partial void OnIxtisasIdChanged();
    partial void OnIQrupIdChanging(System.Nullable<int> value);
    partial void OnIQrupIdChanged();
    partial void OnIAdChanging(string value);
    partial void OnIAdChanged();
    #endregion
		
		public Ixtisa()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IxtisasId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IxtisasId
		{
			get
			{
				return this._IxtisasId;
			}
			set
			{
				if ((this._IxtisasId != value))
				{
					this.OnIxtisasIdChanging(value);
					this.SendPropertyChanging();
					this._IxtisasId = value;
					this.SendPropertyChanged("IxtisasId");
					this.OnIxtisasIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IQrupId", DbType="Int")]
		public System.Nullable<int> IQrupId
		{
			get
			{
				return this._IQrupId;
			}
			set
			{
				if ((this._IQrupId != value))
				{
					this.OnIQrupIdChanging(value);
					this.SendPropertyChanging();
					this._IQrupId = value;
					this.SendPropertyChanged("IQrupId");
					this.OnIQrupIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IAd", DbType="NVarChar(50)")]
		public string IAd
		{
			get
			{
				return this._IAd;
			}
			set
			{
				if ((this._IAd != value))
				{
					this.OnIAdChanging(value);
					this.SendPropertyChanging();
					this._IAd = value;
					this.SendPropertyChanged("IAd");
					this.OnIAdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Qrup")]
	public partial class Qrup : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _QrupId;
		
		private string _QAd;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnQrupIdChanging(int value);
    partial void OnQrupIdChanged();
    partial void OnQAdChanging(string value);
    partial void OnQAdChanged();
    #endregion
		
		public Qrup()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QrupId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int QrupId
		{
			get
			{
				return this._QrupId;
			}
			set
			{
				if ((this._QrupId != value))
				{
					this.OnQrupIdChanging(value);
					this.SendPropertyChanging();
					this._QrupId = value;
					this.SendPropertyChanged("QrupId");
					this.OnQrupIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QAd", DbType="NVarChar(10)")]
		public string QAd
		{
			get
			{
				return this._QAd;
			}
			set
			{
				if ((this._QAd != value))
				{
					this.OnQAdChanging(value);
					this.SendPropertyChanging();
					this._QAd = value;
					this.SendPropertyChanged("QAd");
					this.OnQAdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Universitet")]
	public partial class Universitet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UniversitetId;
		
		private string _Ad;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUniversitetIdChanging(int value);
    partial void OnUniversitetIdChanged();
    partial void OnAdChanging(string value);
    partial void OnAdChanged();
    #endregion
		
		public Universitet()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UniversitetId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UniversitetId
		{
			get
			{
				return this._UniversitetId;
			}
			set
			{
				if ((this._UniversitetId != value))
				{
					this.OnUniversitetIdChanging(value);
					this.SendPropertyChanging();
					this._UniversitetId = value;
					this.SendPropertyChanged("UniversitetId");
					this.OnUniversitetIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ad", DbType="NVarChar(100)")]
		public string Ad
		{
			get
			{
				return this._Ad;
			}
			set
			{
				if ((this._Ad != value))
				{
					this.OnAdChanging(value);
					this.SendPropertyChanging();
					this._Ad = value;
					this.SendPropertyChanged("Ad");
					this.OnAdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Umumi")]
	public partial class Umumi
	{
		
		private int _FakulteId;
		
		private string _FAd;
		
		private System.Nullable<int> _FTehsilFormasiId;
		
		private System.Nullable<int> _FUniversitetId;
		
		private System.Nullable<int> _FIxtisasId;
		
		private string _GirisBali;
		
		private System.Nullable<int> _UniversitetId;
		
		private string _Ad;
		
		private System.Nullable<int> _TehsilFormasiId;
		
		private string _TAd;
		
		private System.Nullable<int> _IxtisasId;
		
		private System.Nullable<int> _IQrupId;
		
		private string _IAd;
		
		private System.Nullable<int> _QrupId;
		
		private string _QAd;
		
		public Umumi()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FakulteId", DbType="Int NOT NULL")]
		public int FakulteId
		{
			get
			{
				return this._FakulteId;
			}
			set
			{
				if ((this._FakulteId != value))
				{
					this._FakulteId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAd", DbType="NVarChar(100)")]
		public string FAd
		{
			get
			{
				return this._FAd;
			}
			set
			{
				if ((this._FAd != value))
				{
					this._FAd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FTehsilFormasiId", DbType="Int")]
		public System.Nullable<int> FTehsilFormasiId
		{
			get
			{
				return this._FTehsilFormasiId;
			}
			set
			{
				if ((this._FTehsilFormasiId != value))
				{
					this._FTehsilFormasiId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FUniversitetId", DbType="Int")]
		public System.Nullable<int> FUniversitetId
		{
			get
			{
				return this._FUniversitetId;
			}
			set
			{
				if ((this._FUniversitetId != value))
				{
					this._FUniversitetId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIxtisasId", DbType="Int")]
		public System.Nullable<int> FIxtisasId
		{
			get
			{
				return this._FIxtisasId;
			}
			set
			{
				if ((this._FIxtisasId != value))
				{
					this._FIxtisasId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GirisBali", DbType="NVarChar(15)")]
		public string GirisBali
		{
			get
			{
				return this._GirisBali;
			}
			set
			{
				if ((this._GirisBali != value))
				{
					this._GirisBali = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UniversitetId", DbType="Int")]
		public System.Nullable<int> UniversitetId
		{
			get
			{
				return this._UniversitetId;
			}
			set
			{
				if ((this._UniversitetId != value))
				{
					this._UniversitetId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ad", DbType="NVarChar(100)")]
		public string Ad
		{
			get
			{
				return this._Ad;
			}
			set
			{
				if ((this._Ad != value))
				{
					this._Ad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TehsilFormasiId", DbType="Int")]
		public System.Nullable<int> TehsilFormasiId
		{
			get
			{
				return this._TehsilFormasiId;
			}
			set
			{
				if ((this._TehsilFormasiId != value))
				{
					this._TehsilFormasiId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAd", DbType="NVarChar(10)")]
		public string TAd
		{
			get
			{
				return this._TAd;
			}
			set
			{
				if ((this._TAd != value))
				{
					this._TAd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IxtisasId", DbType="Int")]
		public System.Nullable<int> IxtisasId
		{
			get
			{
				return this._IxtisasId;
			}
			set
			{
				if ((this._IxtisasId != value))
				{
					this._IxtisasId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IQrupId", DbType="Int")]
		public System.Nullable<int> IQrupId
		{
			get
			{
				return this._IQrupId;
			}
			set
			{
				if ((this._IQrupId != value))
				{
					this._IQrupId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IAd", DbType="NVarChar(50)")]
		public string IAd
		{
			get
			{
				return this._IAd;
			}
			set
			{
				if ((this._IAd != value))
				{
					this._IAd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QrupId", DbType="Int")]
		public System.Nullable<int> QrupId
		{
			get
			{
				return this._QrupId;
			}
			set
			{
				if ((this._QrupId != value))
				{
					this._QrupId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QAd", DbType="NVarChar(10)")]
		public string QAd
		{
			get
			{
				return this._QAd;
			}
			set
			{
				if ((this._QAd != value))
				{
					this._QAd = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
